name: anime_manga_hub
description: A premium Anime and Manga streaming application native clone.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Standard Icons
  cupertino_icons: ^1.0.6
  
  # Networking
  http: ^1.2.0
  
  # State Management & Local Storage
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Image Rendering & Caching for Manga Reader/Posters
  cached_network_image: ^3.3.1
  
  # Native Video Playback
  video_player: ^2.8.5
  chewie: ^1.7.5
  
  # UI Animations
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true